server:
  port: 8080

spring:
  data:
    maria:
      jdbc-url: jdbc:mariadb://192.168.50.251:3306/employees
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: root
    jpa:
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          temp:
            use_jdbc_metadata_defaults: false
      generate-ddl: true